export const countryCodes = [
  { name: 'India', dial_code: '+91', code: 'IN' },
  { name: 'United States', dial_code: '+1', code: 'US' },
  { name: 'United Kingdom', dial_code: '+44', code: 'GB' },
  { name: 'Australia', dial_code: '+61', code: 'AU' },
  { name: 'United Arab Emirates', dial_code: '+971', code: 'AE' },
  { name: 'Canada', dial_code: '+1', code: 'CA' },
  { name: 'Singapore', dial_code: '+65', code: 'SG' },
  { name: 'New Zealand', dial_code: '+64', code: 'NZ' },
  { name: 'Saudi Arabia', dial_code: '+966', code: 'SA' },
  { name: 'South Africa', dial_code: '+27', code: 'ZA' },
  { name: 'Germany', dial_code: '+49', code: 'DE' },
  { name: 'France', dial_code: '+33', code: 'FR' },
  { name: 'Italy', dial_code: '+39', code: 'IT' },
  { name: 'Spain', dial_code: '+34', code: 'ES' },
  { name: 'Netherlands', dial_code: '+31', code: 'NL' },
  { name: 'Sweden', dial_code: '+46', code: 'SE' },
  { name: 'Switzerland', dial_code: '+41', code: 'CH' },
  { name: 'Japan', dial_code: '+81', code: 'JP' },
  { name: 'China', dial_code: '+86', code: 'CN' },
  { name: 'Brazil', dial_code: '+55', code: 'BR' },
  { name: 'Mexico', dial_code: '+52', code: 'MX' },
  { name: 'Russia', dial_code: '+7', code: 'RU' },
  { name: 'South Korea', dial_code: '+82', code: 'KR' },
  { name: 'Turkey', dial_code: '+90', code: 'TR' },
  { name: 'Malaysia', dial_code: '+60', code: 'MY' },
  { name: 'Indonesia', dial_code: '+62', code: 'ID' },
  { name: 'Philippines', dial_code: '+63', code: 'PH' },
  { name: 'Thailand', dial_code: '+66', code: 'TH' },
  { name: 'Vietnam', dial_code: '+84', code: 'VN' },
  { name: 'Pakistan', dial_code: '+92', code: 'PK' },
  { name: 'Bangladesh', dial_code: '+880', code: 'BD' },
  { name: 'Sri Lanka', dial_code: '+94', code: 'LK' },
  { name: 'Nepal', dial_code: '+977', code: 'NP' },
  { name: 'Qatar', dial_code: '+974', code: 'QA' },
  { name: 'Oman', dial_code: '+968', code: 'OM' },
  { name: 'Kuwait', dial_code: '+965', code: 'KW' },
  { name: 'Bahrain', dial_code: '+973', code: 'BH' },
  { name: 'Egypt', dial_code: '+20', code: 'EG' },
  { name: 'Nigeria', dial_code: '+234', code: 'NG' },
  { name: 'Kenya', dial_code: '+254', code: 'KE' },
  { name: 'Argentina', dial_code: '+54', code: 'AR' },
  { name: 'Colombia', dial_code: '+57', code: 'CO' },
  { name: 'Chile', dial_code: '+56', code: 'CL' },
  { name: 'Peru', dial_code: '+51', code: 'PE' },
  { name: 'Venezuela', dial_code: '+58', code: 'VE' },
  { name: 'Afghanistan', dial_code: '+93', code: 'AF' },
  { name: 'Albania', dial_code: '+355', code: 'AL' },
  { name: 'Algeria', dial_code: '+213', code: 'DZ' },
  { name: 'Andorra', dial_code: '+376', code: 'AD' },
  { name: 'Angola', dial_code: '+244', code: 'AO' },
  { name: 'Armenia', dial_code: '+374', code: 'AM' },
  { name: 'Austria', dial_code: '+43', code: 'AT' },
  { name: 'Azerbaijan', dial_code: '+994', code: 'AZ' },
  { name: 'Bahamas', dial_code: '+1', code: 'BS' },
  { name: 'Belarus', dial_code: '+375', code: 'BY' },
  { name: 'Belgium', dial_code: '+32', code: 'BE' },
  { name: 'Belize', dial_code: '+501', code: 'BZ' },
  { name: 'Bolivia', dial_code: '+591', code: 'BO' },
  { name: 'Bulgaria', dial_code: '+359', code: 'BG' },
  { name: 'Cambodia', dial_code: '+855', code: 'KH' },
  { name: 'Cameroon', dial_code: '+237', code: 'CM' },
  { name: 'Costa Rica', dial_code: '+506', code: 'CR' },
  { name: 'Croatia', dial_code: '+385', code: 'HR' },
  { name: 'Cuba', dial_code: '+53', code: 'CU' },
  { name: 'Cyprus', dial_code: '+357', code: 'CY' },
  { name: 'Czech Republic', dial_code: '+420', code: 'CZ' },
  { name: 'Denmark', dial_code: '+45', code: 'DK' },
  { name: 'Ecuador', dial_code: '+593', code: 'EC' },
  { name: 'El Salvador', dial_code: '+503', code: 'SV' },
  { name: 'Estonia', dial_code: '+372', code: 'EE' },
  { name: 'Fiji', dial_code: '+679', code: 'FJ' },
  { name: 'Finland', dial_code: '+358', code: 'FI' },
  { name: 'Georgia', dial_code: '+995', code: 'GE' },
  { name: 'Ghana', dial_code: '+233', code: 'GH' },
  { name: 'Greece', dial_code: '+30', code: 'GR' },
  { name: 'Guatemala', dial_code: '+502', code: 'GT' },
  { name: 'Honduras', dial_code: '+504', code: 'HN' },
  { name: 'Hungary', dial_code: '+36', code: 'HU' },
  { name: 'Iceland', dial_code: '+354', code: 'IS' },
  { name: 'Iran', dial_code: '+98', code: 'IR' },
  { name: 'Iraq', dial_code: '+964', code: 'IQ' },
  { name: 'Ireland', dial_code: '+353', code: 'IE' },
  { name: 'Israel', dial_code: '+972', code: 'IL' },
  { name: 'Jamaica', dial_code: '+1', code: 'JM' },
  { name: 'Jordan', dial_code: '+962', code: 'JO' },
  { name: 'Kazakhstan', dial_code: '+7', code: 'KZ' },
  { name: 'Latvia', dial_code: '+371', code: 'LV' },
  { name: 'Lebanon', dial_code: '+961', code: 'LB' },
  { name: 'Lithuania', dial_code: '+370', code: 'LT' },
  { name: 'Luxembourg', dial_code: '+352', code: 'LU' },
  { name: 'Malta', dial_code: '+356', code: 'MT' },
  { name: 'Morocco', dial_code: '+212', code: 'MA' },
  { name: 'Myanmar', dial_code: '+95', code: 'MM' },
  { name: 'Nicaragua', dial_code: '+505', code: 'NI' },
  { name: 'Norway', dial_code: '+47', code: 'NO' },
  { name: 'Panama', dial_code: '+507', code: 'PA' },
  { name: 'Paraguay', dial_code: '+595', code: 'PY' },
  { name: 'Poland', dial_code: '+48', code: 'PL' },
  { name: 'Portugal', dial_code: '+351', code: 'PT' },
  { name: 'Romania', dial_code: '+40', code: 'RO' },
  { name: 'Senegal', dial_code: '+221', code: 'SN' },
  { name: 'Serbia', dial_code: '+381', code: 'RS' },
  { name: 'Slovakia', dial_code: '+421', code: 'SK' },
  { name: 'Slovenia', dial_code: '+386', code: 'SI' },
  { name: 'Sudan', dial_code: '+249', code: 'SD' },
  { name: 'Syria', dial_code: '+963', code: 'SY' },
  { name: 'Taiwan', dial_code: '+886', code: 'TW' },
  { name: 'Tanzania', dial_code: '+255', code: 'TZ' },
  { name: 'Tunisia', dial_code: '+216', code: 'TN' },
  { name: 'Uganda', dial_code: '+256', code: 'UG' },
  { name: 'Ukraine', dial_code: '+380', code: 'UA' },
  { name: 'Uruguay', dial_code: '+598', code: 'UY' },
  { name: 'Uzbekistan', dial_code: '+998', code: 'UZ' },
  { name: 'Yemen', dial_code: '+967', code: 'YE' },
  { name: 'Zambia', dial_code: '+260', code: 'ZM' },
  { name: 'Zimbabwe', dial_code: '+263', code: 'ZW' }
].sort((a, b) => a.name.localeCompare(b.name));
